version: '3'
services:
  e_shop_app:
    image: 'e_shop_app:latest'
    ports:
      - "9091:9091"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-shop-app
    depends_on:
      - pg_database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg_database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=wp_cicd_project
      - SPRING_DATASOURCE_PASSWORD=test123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  pg_database:
    image: 'postgres:13.1-alpine'
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=wp_cicd_project
      - POSTGRES_PASSWORD=test123
